### ISSUE TITLE
Add thanks note or clear indication that it is based in my original getopts

### ISSUE THREAD

**Issue by ghost** [coderstephen/plugin-getopts#1]
A link to https://github.com/fishery/getopts to show users other "more mature" options would be nice too.

**Comment by sagebind** [comment]
But... it isn't based on your original getopts. Every line of code I wrote by hand myself. I started with a blank slate.

**Comment by ghost** [comment]
Are you sure?  or do we want to go through the whole process again?

**Comment by sagebind** [comment]
> Are you sure? or do we want to go through the whole process again?

What whole process? I swear on my honor that I literally just wrote every line of code in this repository from scratch earlier today. I don't know what you're trying to say.

**Comment by ghost** [comment]
Not only the specification is the same, but implementation wise you are clearly basing this off the original `getopts`, although this implementation is _definitely_ cleaner.

Why not just use the much faster `getopts` I linked above?

>  I don't know what you're trying to say.

I am trying to say that if you don't add the note I will file a DMCA claim.

**Comment by sagebind** [comment]
> Not only the specification is the same, but implementation wise you are clearly basing this off the original `getopts`, albeit this implementation is definitely cleaner.

That's a pretty subjective argument.

> Also, I see this as a waste of time, when you could use the `getopts` I linked above.

That's my prerogative to waste my time though, isn't it?

> I am trying to say that if you don't add the note I will file a DMCA claim.

Because that's the kind of community you want to build around Fish?

**Comment by bucaran** [comment]
You've been warned.

:+1:
